///////////////////////////////////////////////////////////
//  Composite.cs
//  Implementation of the Class Composite
//  Generated by Enterprise Architect
//  Created on:      23-abr.-2026 21:01:42
//  Original author: gaston
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Composite;
using System.CodeDom;
namespace Composite
{
    /// <summary>
    /// This class (a) defines behaviour for components having children, (b) stores
    /// child components, and (c) implements child-related operations in the Component
    /// interface.
    /// </summary>
    public class Familia : Component
    {

        //Seguimos el patrón porque un elemento de tipo familia puede tener muchos hijos...
        private List<Component> components = new List<Component>();

        public string Nombre { get; set; }

        public Guid IdFamilia
        {
            get
            {
                return base.IdComponente;
            }
            set
            {
                base.IdComponente = value;
            }
        }

        /// <summary>
        /// SI O SI HAY QUE ENVIARLE EN EL CTOR UN ELENENTO DE TIPO COMPONENT
        /// </summary>
        public Familia(Component component)
        {
            if(component == null)   
                throw new ArgumentException("No se puede crear una familia sin un componente asociado");

            components.Add(component);
        }

        /// 
        /// <param name="component"></param>
        public override void Add(Component component)
        {
            components.Add(component);
        }

        /// 
        /// <param name="component"></param>
        public override void Remove(Component component)
        {
            //Antes de hacer remove validar que existan al menos 2 elementos.
            if (components.Count < 2)
            {
                throw new InvalidOperationException("No se puede eliminar el último componente de una familia.");
            }

            components.RemoveAll(o => o.IdComponente == component.IdComponente);
        }

        public List<Component> GetComponentes()
        {
            return components;
        }

        public override int CountElements()
        {
            return components.Count;
        }
    }//end Composite

}//end namespace Composite