///////////////////////////////////////////////////////////
//  Leaf.cs
//  Implementation of the Class Leaf
//  Generated by Enterprise Architect
//  Created on:      23-abr.-2026 21:01:40
//  Original author: gaston
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Composite;
namespace Composite
{
    /// <summary>
    /// This class (a) represents leaf objects in the composition, and (b) defines
    /// behaviour for primitive objects in the composition.
    /// </summary>
    public class Patente : Component
    {

        //Las patentes son los permisos individuales de nuestra app
        //Para este año tomamos como válido un modelo de permiso = Pantalla

        public Guid IdPatente
        {
            get
            {
                return base.IdComponente;
            }
            set
            {
                base.IdComponente = value;
            }
        }

        public string Nombre { get; set; } //Esto nos sirve para hacer match con la pantalla X

        public string Descripcion { get; set; }

        public bool IsRoot { get; set; }

        //etc...
        public Patente()
        {

        }


        /// 
        /// <param name="component"></param>
        public override void Add(Component component)
        {

            throw new Exception("No se pueden agregar componentes a una patente, es un leaf");
        }

        /// 
        /// <param name="component"></param>
        public override void Remove(Component component)
        {

            throw new Exception("No se pueden eliminar componentes de una patente, es un leaf");
        }

        public override int CountElements()
        {
            return 0;
        }
    }//end Leaf

}//end namespace Composite